<?php

/**
 * Implements hook_block_info()
 */
function kued_related_block_info() {
  $blocks['kued_related_episode_future'] = array(
    'info' => t('KUED Related Episodes Block - Future'),
  );
  $blocks['kued_related_episode_past'] = array(
    'info' => t('KUED Related Episodes Block - Past'),
  );
  $blocks['kued_related_episode_all'] = array(
    'info' => t('KUED Related Episodes Block - All'),
  );
  $blocks['kued_filler'] = array(
    'info' => t('KUED filler block'),
  );
  $blocks['kued_related_airdates'] = array(
    'info' => t('Episode Airdates'),
	'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_theme().
 */
function kued_related_theme() {
  $module_path = drupal_get_path('module', 'kued_related');
  $base = array(
    'path' => $module_path . "/theme",   
  );
  $items = array(
    'kued_related_airdates_theme' => $base + array(
    	'template' => 'kued-related-airdates--block',
    	'variables' => array('items' => NULL,),
    ),
  ); 
return $items;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function kued_related_block_view($delta = '') {
  //The $delta parameter tells us which block is being requested.
	$block = array();
  switch ($delta) {
    case 'kued_related_episode_future':
      $block['subject'] = t('KUED Related Episodes Block - future');
      $block['content'] = kued_related_episode_contents('future');
      break;

    case 'kued_related_episode_past':
      $block['subject'] = t('KUED Related Episodes Block - Past');
      $block['content'] = kued_related_episode_contents('past');
      break;

    case 'kued_related_episode_all':
      $block['subject'] = t('KUED Related Episodes Block - All');
      $block['content'] = kued_related_episode_contents('all');
      break;
    case 'kued_related_airdates':
      $block['subject'] = t('Episode Airdates');
      $block['content'] = kued_related_airdates('airdates');
      break;
    case 'kued_filler':
      $block['subject'] = t('KUED Filler Block');
      break;
  }
  return $block;
}

/**
 * A module-defined block content function.
 */
function kued_related_episode_contents($delta) {
  switch ($delta) {
    case 'future':
      return kued_related_block_content($delta);
    case 'past':
      return kued_related_block_content($delta);
    case 'all':
      return kued_related_block_content($delta);
    case 'kued_filler':
      return;
  }
}

/**
 * A module-defined block related content function.
 */
function kued_related_airdates($delta = '') {
  if (path_is_admin(current_path())) {
    // Get the series NID from the hidden Drupal path.
    $path = isset($_GET['q']) ? $_GET['q'] : '<front>';
    $path = explode('/', $path);
    $episode_nid = $path[1];
  } else {
    // Get the series NID from the hidden Drupal path.
    $path = isset($_GET['q']) ? $_GET['q'] : '<front>';
    $path = explode('/', $path);
    $episode_nid = $path[1];
  }

  if(is_numeric($episode_nid)) {
    // Current time formatted for searching
	  $node = node_load($episode_nid);

    // Get current time stamp for query
    $time = date('Y-m-d H:i:s', REQUEST_TIME);

		// Episode type specific preprocessing code.
		//$program_id = $vars['node']->field_episode_airdates;
		$program_id = $node->field_program_id;
		if(isset($program_id['und']['0']['value'])) {
			$program_id = $program_id['und']['0']['value'];
			$channels = array('KUED-HD', 'WORLD', 'KIDS CH');
			$i=0;

			// Now cycle through the results
			foreach($channels as $channel) {
			  switch($channel) {
          case 'KUED-HD':
            $channel_title = 'KUED';
            $class = 'kued';
          break;
          case 'WORLD':
            $channel_title = 'The World';
            $class = 'world';
          break;
          case 'KIDS CH':
            $channel_title = 'Kids 24/7';
            $class = 'kids-247';
          break;
			  }
        
				$result = db_query("SELECT fulldate AS airdate FROM protrack_airlist WHERE channel = :channels AND program_id = :pid AND fulldate > :now ORDER BY channel, fulldate", array(':now' => $time,':channels' => $channel, ':pid' => $program_id))->fetchAllKeyed(0,0);
				foreach($result as $date) {
          if($result) {
            $content['airdates'][$channel_title]['class'] = $class;
            $date = strtotime($date);
            $content['airdates'][$channel_title][] = format_date($date, 'long');
          }
        }
      }
    }

    // Reminder Linking
    $reminder = 'Reminder';
    $reminder_long = 'Schedule a reminder';
    $reminder_link = '/reminder/' . $node->nid . '/' . $program_id;
    // Javascript popup link:
    $popup_link = 'onclick=\'window.open("' . $reminder_link . '","pagename","menubar=no,toolbar=no,width=500,height=650,scrollbars=yes,location=0,top=20,left=20");\'';
    $popup_name = 'name=\'' . $node->nid . '-' . $program_id . '\'';
    $reminder_link = 'javascript:void(0)';
    $reminder_link_future = '<a ' . $popup_name . ' ' . $popup_link . ' href=\'' . $reminder_link . '\' title="' . $reminder . ' for ' . $node->title .'" class="reminder reminder-link reminder-link-future">' . $reminder_long . ' <span>for ' . $node->title .'</span></a>';

    if(!empty($content)) {
      $items = array(
        '#items' => $content,
        '#reminder' => $reminder_link_future,
       );
      return theme('kued_related_airdates_theme', array('content' => $items,));
    }
  }
}

/**
 * A module-defined block related content function.
 */
function kued_related_block_content($delta = '') {
	// Build some generic arrays
	$nodes = array();
	$exclude = array();
	$items = array();

  if (path_is_admin(current_path())) {
    // Get the series NID from the hidden Drupal path.
    $path = isset($_GET['q']) ? $_GET['q'] : '<front>';
    $path = explode('/', $path);
    $series_nid = $path[1];
  } else {
    // Get the series NID from the hidden Drupal path.
    $path = isset($_GET['q']) ? $_GET['q'] : '<front>';
    $path = explode('/', $path);
    $series_nid = $path[1];
  }

  if(is_numeric($series_nid)) {
    // Current time formatted for searching
    $now_formatted = date('Y-m-d H:i:s', REQUEST_TIME);
    $future_formatted = date('Y-m-d H:i:s', REQUEST_TIME + 2592000);
    $query = "SELECT DISTINCT ON (field_data_field_program_id, fulldate, channel) field_episode_cross_link_target_id AS nid, fulldate, channel
      FROM field_data_field_episode_cross_link
      LEFT JOIN field_data_field_program_id
      ON (field_data_field_episode_cross_link.field_episode_cross_link_target_id = field_data_field_program_id.entity_id)
      RIGHT JOIN protrack_airlist
      ON (field_data_field_program_id.field_program_id_value = protrack_airlist.program_id)
      WHERE (field_data_field_episode_cross_link.entity_id = :nid)
      AND fulldate > :start
      AND fulldate < :end
      ORDER BY fulldate, channel";
    // Find Future Shows
    $query_array = array(':nid' => $series_nid, ':start' => $now_formatted, ':end' => $future_formatted);
    // Execute the query and build the search loop
    $result = db_query($query, $query_array)->fetchAllKeyed(0,0);
    foreach ($result as $nid) {
      $exclude[] = $nid;
    }

    if($delta == 'future'){
      $items['#prefix'] = '<div id="related-episodes" class="related-episodes related-episodes-future">';
      $items['#suffix'] = '</div>';
  
      $future_formatted = date('Y-m-d H:i:s', REQUEST_TIME + 2592000);
      $query = "SELECT DISTINCT ON (field_data_field_program_id, fulldate, channel) field_episode_cross_link_target_id AS nid, fulldate, channel
        FROM field_data_field_episode_cross_link
        LEFT JOIN field_data_field_program_id
        ON (field_data_field_episode_cross_link.field_episode_cross_link_target_id = field_data_field_program_id.entity_id)
        RIGHT JOIN protrack_airlist
        ON (field_data_field_program_id.field_program_id_value = protrack_airlist.program_id)
        WHERE (field_data_field_episode_cross_link.entity_id = :nid)
        AND fulldate > :start
        AND fulldate < :end
        ORDER BY fulldate, channel";
    
      // Find Future Shows
      $query_array = array(':nid' => $series_nid, ':start' => $now_formatted, ':end' => $future_formatted);
      // Execute the query and build the search loop
      $result = db_query($query, $query_array)->fetchAllKeyed(0,0);
    
      foreach ($result as $nid) {
        $exclude[] = $nid;
        // Open the node
        $node = node_load($nid, $vid = NULL, $reset = TRUE);
        $items[] = node_view($node, 'kued_related_episodes'); // This is where we show the custom content view for program guide items
      }
  
      // Now build the list of nodes
      if(isset($items)) {
        return $items;
      }
    } elseif($delta == 'past') {
      $items['#prefix'] = '<div id="related-episodes" class="related-episodes related-episodes-past">';
      $items['#suffix'] = '</div>';
      // Find Past Shows
      $past_formatted = date('Y-m-d H:i:s', REQUEST_TIME - 2592000);
      $query = "SELECT DISTINCT ON (field_data_field_program_id, fulldate, channel) field_episode_cross_link_target_id AS nid, fulldate, channel
        FROM field_data_field_episode_cross_link
        LEFT JOIN field_data_field_program_id
        ON (field_data_field_episode_cross_link.field_episode_cross_link_target_id = field_data_field_program_id.entity_id)
        RIGHT JOIN protrack_airlist
        ON (field_data_field_program_id.field_program_id_value = protrack_airlist.program_id)
        WHERE (field_data_field_episode_cross_link.entity_id = :nid)
        AND fulldate < :start
        AND fulldate > :end
        ORDER BY fulldate, channel";
      $query_array = array(':nid' => $series_nid, ':start' => $now_formatted, ':end' => $past_formatted);
      // Execute the query and build the search loop
      $result = db_query($query, $query_array)->fetchAllKeyed(0,0);
    
      foreach ($result as $nid) {
        $found = in_array($nid, $exclude);
        if($found != TRUE){
          // load the node
          $node = node_load($nid, $vid = NULL, $reset = TRUE);
          $items[] = node_view($node, 'kued_related_episodes'); // This is where we show the custom content view for program guide items
        }
      }
      // Now build the list of nodes
      if(isset($items)) {
        return $items;
      }
    } elseif($delta == 'all') {
      $items['#prefix'] = '<div id="related-episodes" class="related-episodes related-episodes-all">';
      $items['#suffix'] = '</div>';
      // Find All Shows
      $query = "SELECT DISTINCT ON (field_data_field_program_id, fulldate, channel) field_episode_cross_link_target_id AS nid, fulldate, channel
        FROM field_data_field_episode_cross_link
        LEFT JOIN field_data_field_program_id
        ON (field_data_field_episode_cross_link.field_episode_cross_link_target_id = field_data_field_program_id.entity_id)
        RIGHT JOIN protrack_airlist
        ON (field_data_field_program_id.field_program_id_value = protrack_airlist.program_id)
        WHERE (field_data_field_episode_cross_link.entity_id = :nid)
        AND fulldate > :start
        AND fulldate < :end
        ORDER BY fulldate, channel";
      // Find Future Shows
      $query_array = array(':nid' => $series_nid, ':start' => $now_formatted, ':end' => $future_formatted);
      // Execute the query and build the search loop
      $result = db_query($query, $query_array)->fetchAllKeyed(0,0);
      foreach ($result as $nid) {
        // load the node
        $node = node_load($nid, $vid = NULL, $reset = TRUE);
        if($node->status == 1) {
          $items[] = node_view($node, 'kued_related_episodes'); // This is where we show the custom content view for program guide items
        }
      }
      // Now build the list of nodes
      if(isset($items)) {
        return $items;
      }
    }
	}
}

/**
 * Impliments hook_preprocess_node
 */
function kued_related_preprocess_node(&$vars) {
  if($vars['elements']['#view_mode'] == 'full' || $vars['elements']['#view_mode'] == 'kued_related_episodes') {
    
  $vars['view'] = $vars['elements']['#view_mode'];
    if(isset($vars['field_episode_guide'][0]['value'])) {
      $vars['read_more'] = '<a href="' . $vars['node_url'] . '" title="' . $vars['title'] . ' - Read More">Read More &raquo;</a>';
    } else {
      $vars['read_more'] = '';
    }
  
    if(isset($vars['field_episode_hdtv'][0]['value'])) {
      $vars['hdtv'] = $vars['field_episode_hdtv'][0]['value'];
    } else {
      $vars['hdtv'] = '';
    }
  
    if(isset($vars['closed_caption'])) {
      $vars['closed_caption'] = '<img src="/' . $vars['directory'] . '/images/kued-icon-closed-caption.gif" alt="KUED Closed Caption Icon" />';
    } else {
      $vars['closed_caption'] = '';
    }
  
    if(!empty($vars['field_episode_stereo'])) {
      $terms = $vars['field_episode_stereo'];
      $i=0;
      foreach($terms as $value) {
        if(is_object(isset($value['taxonomy_term']))) {
          $vars['stereo_format'] = $value['taxonomy_term']->name;
          $i++;
        }
      }
      if(isset($vars['stereo_format'])) {
        if($vars['stereo_format'] == 'Mono') {
          $vars['stereo_format'] = '<img src="/' . $vars['directory'] . '/images/kued-icon-mono.gif" alt="KUED Mono Icon" />';
        } elseif($vars['stereo_format'] == 'Stereo') {
          $vars['stereo_format'] = '<img src="/' . $vars['directory'] . '/images/kued-icon-stereo.gif" alt="KUED Stereo Icon" />';
        } elseif($vars['stereo_format'] == 'Stereo Surround 5.1') {
          $vars['stereo_format'] = '<img src="/' . $vars['directory'] . '/images/kued-icon-surround.gif" alt="KUED 5.1 Surround Sound Icon" />';
        } else {
          $vars['stereo_format'] = '';
        }
      } else {
        $vars['stereo_format'] = '';
      }
    }
	}
}

/**
 * Seconds converter
 */
function kued_related_seconds_converstion($time){
  if(is_numeric($time)){
    $value = array(
      "years" => 0, "days" => 0, "hours" => 0,
      "minutes" => 0, "seconds" => 0,
    );
    if($time >= 31556926){
      $value["years"] = floor($time/31556926);
      $time = ($time%31556926);
    }
    if($time >= 86400){
      $value["days"] = floor($time/86400);
      $time = ($time%86400);
    }
    if($time >= 3600){
      $value["hours"] = floor($time/3600);
      $time = ($time%3600);
    }
    if($time >= 60){
      $value["minutes"] = floor($time/60);
      $time = ($time%60);
    }
    $value["seconds"] = floor($time);
    return (array) $value;
  }else{
    return (bool) FALSE;
  }
}

/**
 * Implements hook_entity_info_alter().
 */
function kued_related_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['kued_related_episodes'] = array(
    'label' => t('Related Episodes Display'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['kued_related_slideshow'] = array(
    'label' => t('Related Slideshow Display'),
    'custom settings' => TRUE,
  );
}
